version: "3.9"
services:
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "norrahorse"
    ports:
      - 4306:3306
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
    depends_on: 
      - db
    command: sh -c "
    php bin/console --no-interaction doctrine:migrations:migrate && 
    php bin/console --no-interaction doctrine:fixtures:load && 
    a2enmod rewrite &&
    apache2ctl -D FOREGROUND"
    restart: on-failure